/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  MockFollowModule,
  MockFollowModuleInterface,
} from "../MockFollowModule";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "profileId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "followNFTTokenId",
        type: "uint256",
      },
    ],
    name: "followModuleTransferHook",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "profileId",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "initializeFollowModule",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "follower",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "profileId",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "processFollow",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "profileId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "follower",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "followNFTTokenId",
        type: "uint256",
      },
    ],
    name: "validateFollow",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610357806100206000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c80630e096ae1146100515780633cb22cc4146100675780639713958a14610075578063b4616a2a1461009e575b600080fd5b61006561005f366004610194565b50505050565b005b61006561005f3660046101ee565b610088610083366004610232565b6100b1565b604051610095919061027e565b60405180910390f35b6100656100ac3660046102d3565b505050565b606060006100c183850185610308565b9050806001146101175760405162461bcd60e51b815260206004820152601960248201527f4d6f636b466f6c6c6f774d6f64756c653a20696e76616c696400000000000000604482015260640160405180910390fd5b50506040805160008152602081019091529392505050565b80356001600160a01b038116811461014657600080fd5b919050565b60008083601f84011261015d57600080fd5b50813567ffffffffffffffff81111561017557600080fd5b60208301915083602082850101111561018d57600080fd5b9250929050565b600080600080606085870312156101aa57600080fd5b6101b38561012f565b935060208501359250604085013567ffffffffffffffff8111156101d657600080fd5b6101e28782880161014b565b95989497509550505050565b6000806000806080858703121561020457600080fd5b843593506102146020860161012f565b92506102226040860161012f565b9396929550929360600135925050565b60008060006040848603121561024757600080fd5b83359250602084013567ffffffffffffffff81111561026557600080fd5b6102718682870161014b565b9497909650939450505050565b600060208083528351808285015260005b818110156102ab5785810183015185820160400152820161028f565b818111156102bd576000604083870101525b50601f01601f1916929092016040019392505050565b6000806000606084860312156102e857600080fd5b833592506102f86020850161012f565b9150604084013590509250925092565b60006020828403121561031a57600080fd5b503591905056fea26469706673582212209b3a441366d3f020e492bcd0ed1ecb21e67f9a0c79b6f57e5f7f9370bc1f5a3164736f6c634300080a0033";

type MockFollowModuleConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockFollowModuleConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockFollowModule__factory extends ContractFactory {
  constructor(...args: MockFollowModuleConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<MockFollowModule> {
    return super.deploy(overrides || {}) as Promise<MockFollowModule>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): MockFollowModule {
    return super.attach(address) as MockFollowModule;
  }
  connect(signer: Signer): MockFollowModule__factory {
    return super.connect(signer) as MockFollowModule__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockFollowModuleInterface {
    return new utils.Interface(_abi) as MockFollowModuleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MockFollowModule {
    return new Contract(address, _abi, signerOrProvider) as MockFollowModule;
  }
}
